### PR TITLE
ci: add dependabot

### LINKED ISSUE #225: Set dependabot to make PR automatically, which update pyproject based on security alerts

### PR DESCRIPTION
**Pull request by k1lgor**
# Initial discussions

- [x] Github issue: #225

# Types of changes

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Test (add, remove, modify test(s))
- [x] Other

# What I did

Add dependabot to check on daily basis
and resolves #225 

Dependabot needs to be enabled from the Security tab as well
image

# How I did it

# I am not sure about

# How I tested

# I'm not a dummy, so I've checked these

- [ ] 📑 I documented correctly following our [guidelines](./CONTRIBUTING.md)
- [ ] 💯 I tested locally and it is working
- [x] 🟢 My code does not fail neither code linting checks nor unit test.

Thank you!

### CODE REVIEW

**Comment by Minipada** [comment]
Hi @k1lgor !
Thanks for your pr!

I have some questions. This repo both uses poetry and requirements.txt and requirements-dev.txt and I would like all to be handled. Is it possible with dependabot?

**Comment by k1lgor** [comment]
Hi @Minipada.
So basically `package-ecosystem` must update and poetry packages as well. Here is some [example](https://github.com/exasol/python-toolbox/blob/dcd4ae5f2bdac77298564fa4079149118fd40869/exasol/toolbox/templates/github/dependabot.yml#L12) from other repo which uses only poetry.
About the two req.txt files it could be done like this:
```yaml
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    security:
      open-pull-requests-limit: 5
    path-filters:
      - path: "requirements.txt"
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    security:
      open-pull-requests-limit: 5
    path-filters:
      - path: "requirements-dev.txt"
```
and I can add a check for gh actions as well.

**Comment by k1lgor** [comment]
if this didn't work, we could change it to `package-ecosystem: "poetry"`

**Comment by Minipada** [comment]
Yes please, if you could check for both poetry and pip for dependabot along with dev environment, it would be great. If not possible, i will investigate, maybe I drop the requirements.txt ...

**Comment by k1lgor** [comment]
As per official documentation 
image
poetry is covered when `package-ecosystem` is set to `pip` and the `interval` could be weekly, or monthly as well.
```yaml
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    security:
      open-pull-requests-limit: 5
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    security:
      open-pull-requests-limit: 5
```

**Comment by k1lgor** [comment]
close due to inactivity from owner

**Pull request closed without merging**
